// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PlantaCoreAPI.Infrastructure.Dados;

#nullable disable

namespace PlantaCoreAPI.Infrastructure.Migrations
{
    [DbContext(typeof(PlantaCoreDbContext))]
    [Migration("20260318210918_RecreateDatabase")]
    partial class RecreateDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PlantaCoreAPI.Domain.Entities.Comentario", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("conteudo");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DataExclusao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_exclusao");

                    b.Property<int>("PontuacaoTotal")
                        .HasColumnType("integer")
                        .HasColumnName("pontuacao_total");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid")
                        .HasColumnName("post_id");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("PostId")
                        .HasDatabaseName("ix_comentarios_post_id");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_comentarios_usuario_id");

                    b.ToTable("comentarios", (string)null);
                });

            modelBuilder.Entity("PlantaCoreAPI.Domain.Entities.Comunidade", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativa");

                    b.Property<Guid>("CriadorId")
                        .HasColumnType("uuid")
                        .HasColumnName("criador_id");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<string>("FotoComunidade")
                        .HasColumnType("text")
                        .HasColumnName("foto_comunidade");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.HasIndex("CriadorId");

                    b.HasIndex("Nome")
                        .HasDatabaseName("ix_comunidades_nome");

                    b.ToTable("comunidades", (string)null);
                });

            modelBuilder.Entity("PlantaCoreAPI.Domain.Entities.Curtida", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ComentarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("comentario_id");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("PostId")
                        .HasColumnType("uuid")
                        .HasColumnName("post_id");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("PostId")
                        .HasDatabaseName("ix_curtidas_post_id");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_curtidas_usuario_id");

                    b.HasIndex("ComentarioId", "UsuarioId")
                        .IsUnique()
                        .HasDatabaseName("ix_curtidas_comentario_usuario")
                        .HasFilter("comentario_id IS NOT NULL");

                    b.HasIndex("PostId", "UsuarioId")
                        .IsUnique()
                        .HasDatabaseName("ix_curtidas_post_usuario")
                        .HasFilter("post_id IS NOT NULL");

                    b.ToTable("curtidas", (string)null);
                });

            modelBuilder.Entity("PlantaCoreAPI.Domain.Entities.MembroComunidade", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ComunidadeId")
                        .HasColumnType("uuid")
                        .HasColumnName("comunidade_id");

                    b.Property<DateTime>("DataEntrada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_entrada")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("EhAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("eh_admin");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("ComunidadeId", "UsuarioId")
                        .IsUnique()
                        .HasDatabaseName("ix_membros_comunidade_unico");

                    b.ToTable("membros_comunidade", (string)null);
                });

            modelBuilder.Entity("PlantaCoreAPI.Domain.Entities.Notificacao", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DataDelecao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_delecao");

                    b.Property<DateTime?>("DataLeitura")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_leitura");

                    b.Property<bool>("Lida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("lida");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mensagem");

                    b.Property<Guid?>("PlantaId")
                        .HasColumnType("uuid")
                        .HasColumnName("planta_id");

                    b.Property<Guid?>("PostId")
                        .HasColumnType("uuid")
                        .HasColumnName("post_id");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<Guid?>("UsuarioOrigemId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_origem_id");

                    b.HasKey("Id");

                    b.HasIndex("PlantaId")
                        .HasDatabaseName("ix_notificacoes_planta_id");

                    b.HasIndex("PostId")
                        .HasDatabaseName("ix_notificacoes_post_id");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_notificacoes_usuario_id");

                    b.HasIndex("UsuarioOrigemId")
                        .HasDatabaseName("ix_notificacoes_usuario_origem_id");

                    b.ToTable("notificacoes", (string)null);
                });

            modelBuilder.Entity("PlantaCoreAPI.Domain.Entities.Planta", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Cuidados")
                        .HasColumnType("text")
                        .HasColumnName("cuidados");

                    b.Property<string>("DadosPlantNet")
                        .HasColumnType("text")
                        .HasColumnName("dados_plantnet");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("DataIdentificacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_identificacao");

                    b.Property<string>("DescricaoToxicidade")
                        .HasColumnType("text")
                        .HasColumnName("descricao_toxicidade");

                    b.Property<string>("DescricaoToxicidadeAnimais")
                        .HasColumnType("text")
                        .HasColumnName("descricao_toxicidade_animais");

                    b.Property<string>("DescricaoToxicidadeCriancas")
                        .HasColumnType("text")
                        .HasColumnName("descricao_toxicidade_criancas");

                    b.Property<string>("Familia")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("familia");

                    b.Property<string>("FotoPlanta")
                        .HasColumnType("text")
                        .HasColumnName("foto_url");

                    b.Property<string>("Genero")
                        .HasColumnType("text")
                        .HasColumnName("genero");

                    b.Property<string>("NomeCientifico")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("nome_cientifico");

                    b.Property<string>("NomeComum")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("nome_comum");

                    b.Property<string>("RequisitosAgua")
                        .HasColumnType("text")
                        .HasColumnName("requisitos_agua");

                    b.Property<string>("RequisitosLuz")
                        .HasColumnType("text")
                        .HasColumnName("requisitos_luz");

                    b.Property<string>("RequisitosTemperatura")
                        .HasColumnType("text")
                        .HasColumnName("requisitos_temperatura");

                    b.Property<bool>("Toxica")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("toxica");

                    b.Property<bool>("ToxicaAnimais")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("toxica_animais");

                    b.Property<bool>("ToxicaCriancas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("toxica_criancas");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_plantas_usuario_id");

                    b.ToTable("plantas", (string)null);
                });

            modelBuilder.Entity("PlantaCoreAPI.Domain.Entities.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<Guid?>("ComunidadeId")
                        .HasColumnType("uuid")
                        .HasColumnName("comunidade_id");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("conteudo");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DataExclusao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_exclusao");

                    b.Property<Guid?>("PlantaId")
                        .HasColumnType("uuid")
                        .HasColumnName("planta_id");

                    b.Property<int>("PontuacaoTotal")
                        .HasColumnType("integer")
                        .HasColumnName("pontuacao_total");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("ComunidadeId")
                        .HasDatabaseName("ix_posts_comunidade_id");

                    b.HasIndex("PlantaId")
                        .HasDatabaseName("ix_posts_planta_id");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_posts_usuario_id");

                    b.ToTable("posts", (string)null);
                });

            modelBuilder.Entity("PlantaCoreAPI.Domain.Entities.SolicitacaoSeguir", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AlvoId")
                        .HasColumnType("uuid")
                        .HasColumnName("alvo_id");

                    b.Property<DateTime>("DataSolicitacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_solicitacao")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("Pendente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("pendente");

                    b.Property<Guid>("SolicitanteId")
                        .HasColumnType("uuid")
                        .HasColumnName("solicitante_id");

                    b.HasKey("Id");

                    b.HasIndex("AlvoId");

                    b.HasIndex("SolicitanteId", "AlvoId")
                        .HasDatabaseName("ix_solicitacoes_seguir_par");

                    b.ToTable("solicitacoes_seguir", (string)null);
                });

            modelBuilder.Entity("PlantaCoreAPI.Domain.Entities.TokenRefresh", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("DataExpiracao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_expiracao");

                    b.Property<DateTime?>("DataRevogacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_revogacao");

                    b.Property<bool>("Revogado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("revogado");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("token");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_tokens_refresh_token");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_tokens_refresh_usuario_id");

                    b.ToTable("tokens_refresh", (string)null);
                });

            modelBuilder.Entity("PlantaCoreAPI.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<string>("Biografia")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("biografia");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DataExclusao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_exclusao");

                    b.Property<DateTime?>("DataTokenResetarSenha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_token_resetar");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("email_confirmado");

                    b.Property<string>("FotoPerfil")
                        .HasColumnType("text")
                        .HasColumnName("foto_perfil");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nome");

                    b.Property<bool>("PerfilPrivado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("perfil_privado");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("senha_hash");

                    b.Property<string>("TokenConfirmacaoEmail")
                        .HasColumnType("text")
                        .HasColumnName("token_confirmacao_email");

                    b.Property<string>("TokenResetarSenha")
                        .HasColumnType("text")
                        .HasColumnName("token_resetar_senha");

                    b.HasKey("Id");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("seguidores", b =>
                {
                    b.Property<Guid>("seguidor_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("seguido_id")
                        .HasColumnType("uuid");

                    b.HasKey("seguidor_id", "seguido_id");

                    b.HasIndex("seguido_id");

                    b.ToTable("seguidores", (string)null);
                });

            modelBuilder.Entity("PlantaCoreAPI.Domain.Entities.Comentario", b =>
                {
                    b.HasOne("PlantaCoreAPI.Domain.Entities.Post", "Post")
                        .WithMany("Comentarios")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comentarios_posts");

                    b.HasOne("PlantaCoreAPI.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comentarios_usuarios");

                    b.Navigation("Post");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PlantaCoreAPI.Domain.Entities.Comunidade", b =>
                {
                    b.HasOne("PlantaCoreAPI.Domain.Entities.Usuario", "Criador")
                        .WithMany()
                        .HasForeignKey("CriadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_comunidades_criador");

                    b.Navigation("Criador");
                });

            modelBuilder.Entity("PlantaCoreAPI.Domain.Entities.Curtida", b =>
                {
                    b.HasOne("PlantaCoreAPI.Domain.Entities.Comentario", "Comentario")
                        .WithMany("Curtidas")
                        .HasForeignKey("ComentarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_curtidas_comentarios");

                    b.HasOne("PlantaCoreAPI.Domain.Entities.Post", "Post")
                        .WithMany("Curtidas")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_curtidas_posts");

                    b.HasOne("PlantaCoreAPI.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_curtidas_usuarios");

                    b.Navigation("Comentario");

                    b.Navigation("Post");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PlantaCoreAPI.Domain.Entities.MembroComunidade", b =>
                {
                    b.HasOne("PlantaCoreAPI.Domain.Entities.Comunidade", "Comunidade")
                        .WithMany("Membros")
                        .HasForeignKey("ComunidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_membros_comunidade");

                    b.HasOne("PlantaCoreAPI.Domain.Entities.Usuario", "Usuario")
                        .WithMany("ComunidadesParticipantes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_membros_comunidade_usuario");

                    b.Navigation("Comunidade");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PlantaCoreAPI.Domain.Entities.Notificacao", b =>
                {
                    b.HasOne("PlantaCoreAPI.Domain.Entities.Planta", "Planta")
                        .WithMany()
                        .HasForeignKey("PlantaId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_notificacoes_plantas");

                    b.HasOne("PlantaCoreAPI.Domain.Entities.Post", "Post")
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_notificacoes_posts");

                    b.HasOne("PlantaCoreAPI.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Notificacoes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notificacoes_usuarios");

                    b.HasOne("PlantaCoreAPI.Domain.Entities.Usuario", "UsuarioOrigem")
                        .WithMany()
                        .HasForeignKey("UsuarioOrigemId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_notificacoes_usuarios_origem");

                    b.Navigation("Planta");

                    b.Navigation("Post");

                    b.Navigation("Usuario");

                    b.Navigation("UsuarioOrigem");
                });

            modelBuilder.Entity("PlantaCoreAPI.Domain.Entities.Planta", b =>
                {
                    b.HasOne("PlantaCoreAPI.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Plantas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_plantas_usuarios");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PlantaCoreAPI.Domain.Entities.Post", b =>
                {
                    b.HasOne("PlantaCoreAPI.Domain.Entities.Comunidade", "Comunidade")
                        .WithMany("Posts")
                        .HasForeignKey("ComunidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_posts_comunidades");

                    b.HasOne("PlantaCoreAPI.Domain.Entities.Planta", "Planta")
                        .WithMany("Posts")
                        .HasForeignKey("PlantaId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_posts_plantas");

                    b.HasOne("PlantaCoreAPI.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Posts")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_posts_usuarios");

                    b.Navigation("Comunidade");

                    b.Navigation("Planta");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PlantaCoreAPI.Domain.Entities.SolicitacaoSeguir", b =>
                {
                    b.HasOne("PlantaCoreAPI.Domain.Entities.Usuario", "Alvo")
                        .WithMany("SolicitacoesSeguirRecebidas")
                        .HasForeignKey("AlvoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_solicitacoes_seguir_alvo");

                    b.HasOne("PlantaCoreAPI.Domain.Entities.Usuario", "Solicitante")
                        .WithMany("SolicitacoesSeguirEnviadas")
                        .HasForeignKey("SolicitanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_solicitacoes_seguir_solicitante");

                    b.Navigation("Alvo");

                    b.Navigation("Solicitante");
                });

            modelBuilder.Entity("PlantaCoreAPI.Domain.Entities.TokenRefresh", b =>
                {
                    b.HasOne("PlantaCoreAPI.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tokens_refresh_usuarios");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("seguidores", b =>
                {
                    b.HasOne("PlantaCoreAPI.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("seguido_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlantaCoreAPI.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("seguidor_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PlantaCoreAPI.Domain.Entities.Comentario", b =>
                {
                    b.Navigation("Curtidas");
                });

            modelBuilder.Entity("PlantaCoreAPI.Domain.Entities.Comunidade", b =>
                {
                    b.Navigation("Membros");

                    b.Navigation("Posts");
                });

            modelBuilder.Entity("PlantaCoreAPI.Domain.Entities.Planta", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("PlantaCoreAPI.Domain.Entities.Post", b =>
                {
                    b.Navigation("Comentarios");

                    b.Navigation("Curtidas");
                });

            modelBuilder.Entity("PlantaCoreAPI.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("ComunidadesParticipantes");

                    b.Navigation("Notificacoes");

                    b.Navigation("Plantas");

                    b.Navigation("Posts");

                    b.Navigation("SolicitacoesSeguirEnviadas");

                    b.Navigation("SolicitacoesSeguirRecebidas");
                });
#pragma warning restore 612, 618
        }
    }
}
